name: Setup
description: Setup Node.js and install dependencies


runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 22.x
        cache: npm
        cache-dependency-path: package-lock.json
        registry-url: https://registry.npmjs.org

    - name: Upgrade npm for OIDC support
      run: npm install -g npm@latest
      shell: bash

    - name: Restore node_modules cache
      id: modules-cache
      uses: actions/cache@v4
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      if: steps.modules-cache.outputs.cache-hit != 'true'
      run: npm install --frozen-lockfile
      shell: bash
